// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eljaroboard.Data;

namespace eljaroboard.Data.Migrations
{
    [DbContext(typeof(BoardContext))]
    [Migration("20201201134610_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("eljaroboard.Data.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatorID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Downticks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Upticks")
                        .HasColumnType("INTEGER");

                    b.HasKey("CardId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
